version: '3.8'

name: datn

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: DATN-app
    #restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_EXTERNAL_PORT=${REDIS_EXTERNAL_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_MAXMEMORY=${REDIS_MAXMEMORY}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_HZ=${REDIS_HZ}
      # - DATABASE_URL=${DATABASE_URL}
    networks:
      - DATN-network
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    dns:
      - 8.8.8.8
      - 1.1.1.1
  db:
    image: pgvector/pgvector:pg15
    restart: always
    container_name: DATN-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - DATN_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - DATN-network  
  redis:
    image: redis:7.4.1-alpine
    container_name: DATN-redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    volumes:
      - DATN_redis_data:/data # Persist Redis data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory ${REDIS_MAXMEMORY}
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
      --tcp-backlog 511
      --tcp-keepalive 60
      --timeout ${REDIS_TIMEOUT}
      --hz ${REDIS_HZ}  
    networks:
      - DATN-network  

volumes:
  DATN_postgres_data: {}
  DATN_redis_data: {}

networks:
  DATN-network: {}